Tune testing for github 403 errors

diff --git a/.github/workflows/cohd-monitor.yml b/.github/workflows/cohd-monitor.yml
--- a/.github/workflows/cohd-monitor.yml
+++ b/.github/workflows/cohd-monitor.yml
@@ -24,8 +24,7 @@ jobs:
       id: dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pytest requests pandas matplotlib linkml-runtime bmt reasoner-validator>=4.0.0 flask flask-cors flask-caching
-        pip show reasoner-validator
+        pip install pytest requests 
 
       # Run /health checks on all COHD instances (dev, CI, Test, Prod)
     - name: Test all COHD instances alive
@@ -34,20 +33,20 @@ jobs:
       run: |
         pytest -s test_alive.py
 
-      # Test cohd.io by running pytest on test_cohd_io.py
-    - name: Test COHD REST API
-      if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
-      run: |
-        pytest -s test_cohd_io.py
+    #   # Test cohd.io by running pytest on test_cohd_io.py
+    # - name: Test COHD REST API
+    #   if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
+    #   run: |
+    #     pytest -s test_cohd_io.py
 
-      # Test COHD TRAPI endpoints by running pytest on test_cohd_trapi.py
-    - name: Test COHD TRAPI
-      if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
-      run: |
-        pytest -s test_cohd_trapi.py
+    #   # Test COHD TRAPI endpoints by running pytest on test_cohd_trapi.py
+    # - name: Test COHD TRAPI
+    #   if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
+    #   run: |
+    #     pytest -s test_cohd_trapi.py
 
-      # Test covid.cohd.io by running pytest on test_cohd_covid_io.py
-    - name: Test covid.cohd.io
-      if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
-      run: |
-        pytest -s test_cohd_covid_io.py
+    #   # Test covid.cohd.io by running pytest on test_cohd_covid_io.py
+    # - name: Test covid.cohd.io
+    #   if: success() || (failure() && steps.dependencies.conclusion == 'success')  # Run even if other tests fail
+    #   run: |
+    #     pytest -s test_cohd_covid_io.py
